### ISSUE TITLE
URC Competition

### ISSUE THREAD

**Issue by Weffe** [teamr3/URC-18#2]
Hey there!

I was searching repos by the topic name: URC and you guys popped up! I am part of Titan Rover and just wanted to say hello :hand: We are also working to compete in the upcoming URC and are actually transitioning to using a Nvidia Tegra like you guys so maybe we can help each other out if we run into any issues. Honestly, would just be really interesting to share ideas and help each other out. 

Check us out: [Titan Rover](https://github.com/CSUFTitanRover)

**Comment by danielsnider** [comment]
That's awesome! I'm glad you found us. We recently wrote up how our robot works. Check out our book chapter about URC here:
https://github.com/danielsnider/ros-rover/blob/master/Book%20Chapter%20-%20University%20Rover%20Challenge%20Tutorials%20and%20Control%20System%20Survey.pdf

**Comment by Weffe** [comment]
Niceeeeeeee :ok_hand:

**Comment by mincrmatt12** [comment]
Also the repo in that Readme is for last year's code

**Comment by Weffe** [comment]
Okay cool, I am trying to set things up for my team this year to use Sphinx for our docs. As last year our docs were not that good. Hopefully, we can start setting up some docs for our layout and I can share them with you if you are interested.

**Comment by mincrmatt12** [comment]
Ya we're trying to use sphinx too, see the docs/ folder. It's not that hard to set it up, just run `sphinx-quickstart` in a docs folder and answer sensibly. Then just setup readthedocs and point it to your repo.

**Comment by mincrmatt12** [comment]
closed for lack of discussion
