### ISSUE TITLE
Jetpack for Nvidia Jetson

### ISSUE THREAD

**Issue by Weffe** [teamr3/URC-18#8]
Hey guys,

It's been a while since we chatted but our team is using the Nvidia Jetson TX2 and we are running into issues getting Jetpack working for it. Have you guys installed Jetpack on the TX1? And if you have, how was the process?

Thanks!

**Comment by GabeCasciano** [comment]
We just got 2 TX2's and havent had a chance to jetpack them yet. As for the TX1 that was almost a year ago and I dont know if any of us can comment on that, I do remember running into some issues though.

**Comment by Weffe** [comment]
Oh cool! Yeah we are running into issues getting jetpack working on the tx2. If you guys are able to get jetpack installed then let me know :)

**Comment by yanga001** [comment]
If you still need help please leave a comment, we installed successfully on the TX2. Otherwise @mincrmatt12  @GabeCasciano close the issue

**Comment by mincrmatt12** [comment]
I'm closing for now, I'll reopen if required.
